apiVersion: backstage.io/v1alpha1
kind: Website
metadata: 
  name: testing-name-change
  description: Core platform service that can ingest logged user actions from Galileo applications and services
  annotations: 
    backstage.io/techdocs-ref: "dir:./"
  tags: 
    - python
    - rest-api
spec: 
  lifecycle: production
  owner: GalileoDigital
  type: website
  system: public-websites